name: "ittp/ssh-workflow"
description: "SSH Workflow"
author: "ittp"
branding:
  icon: "chevron-up"
  color: "gray-dark"
inputs:
  host:
    description: "SSH Host"
    required: true
    default: ""
  user:
    description: "User"
    required: true
    default: "root"
  password:
    description: "Password"
    required: true
    default: ""
  script:
    description: "Script to Run"
    required: true
    default: ""
  port:
    description: "Port"
    required: true
    default: "22"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.host }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.script }}
    - ${{ inputs.port }}
