name: "SSH"
description: ""
inputs:
  host:
    description: "SSH Host"
    required: true
    default: ""
  user:
    description: "User name"
    required: true
    default: ""
  password:
    description: "User Password"
    required: true
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.host }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
