name: Docker Image CI

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: ./ssh-workflow
      with:
        host: ${{ secrets.host }}
        user: ${{ secrets.user }}
        password: ${{ secrets.password }}
        script: "echo This Workflow is Awesome!"
        port: ${{ secrets.port }}
