on: [push]

jobs:
  ssh-job:
    runs-on: ubuntu-latest
    name: A job to SSH
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Step
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
